[OPTIONS]
nordvpn-ovpn-files-path = /path/to/nordvpn-ovpn-files
ipvanish-ovpn-files-path = /path/to/ipvanish-ovpn-files
screen-width = 1366
screen-height = 768
up-taskbar-height = 5

[WAIT_CONDITIONS]
implicitly-wait-time = 15

[WEB_DRIVERS]
base-location = /SeleniumWebDrivers
chrome-location = /Chrome
chrome-webdriver = /chromedriver
gecko-location = /Gecko
gecko-webdriver = /geckodriver
firefox-location = /Gecko
firefox-webdriver = /geckodriver

[BOT]
max-alive-time = 90
min-alive-time = 65
run-infinitely = True

[OVPN]
max-connect-retries = 1
max-wait-time = 7

[SCROLL]
px-value = 250

[BROWSER]
chrome-binary-location = /bin/google-chrome-stable
firefox-binary-location = /opt/firefox/firefox

[ADS]
providers = propeller-ads
attr = class
attr-name = image-block
close-attr = class
close-attr-name = btoa

[PROXY]
proxy-product = smartproxy.com
proxy-geo-target-area = gate
proxy-session-duration = 2
proxy-username = adfrpr
proxy-password = y4nSMS602jww
proxy-port = 10000
proxy-sticky-template = user-<user>-country-<geo_target>:<pass>@<geo_target_area>.smartproxy.com:<port>
proxy-random-template = user-<user>:<pass>@gate.smartproxy.com:10000

[IDENTITY]
# the following variable dictates on what base to fetch identity, the accepted values are 'scr'(screen resolution),
# 'device_type', 'proxy_geo'(careful here), 'id'(be careful with this one - very careful). If using screen-resolution,
# no need to set value
fetch-by = scr
fetch-by-value =