[OPTIONS]
nordvpn-ovpn-files-path = /path/to/nordvpn-ovpn-files
ipvanish-ovpn-files-path = /path/to/ipvanish-ovpn-files
screen-width = 1366
screen-height = 768
up-taskbar-height = 5
debug = True

[WAIT_CONDITIONS]
implicitly-wait-time = 15

[WEB_DRIVERS]
base-location = /SeleniumWebDrivers
chrome-location = /Chrome
chrome-webdriver = /chromedriver
gecko-location = /Gecko
gecko-webdriver = /geckodriver
firefox-location = /Gecko
firefox-webdriver = /geckodriver

[BOT]
bot-id = 1376-0
max-alive-time = 120
min-alive-time = 100
run-infinitely = True
# Don't touch mouse-use-probability unless you know what it does
mouse-use-probability = 0.62

[OVPN]
max-connect-retries = 1
max-wait-time = 7

[SCROLL]
px-value = 250

[BROWSER]
chrome-binary-location = /bin/google-chrome-stable
firefox-binary-location = /opt/firefox/firefox

[SITE]
proxy-whitelisted-domains = whouseem.com,dudialgator.com,bedrapiona.com,fleraprt.com
proxy-blacklisted-domains = googleapis,chrome,google,gstatic,gvt1,finnsec.us
proxy-blacklisted-extensions = .html,.js,.css,.jpg,.jpeg,.png,.gif,.svg,.woff,.woff2,.ttf,.ico,.webm,.ogg,.wav,.mp3,.mp4
allow-url-through-proxy-if-matches-browser-active-url = True

[PROXY]
proxy-product = proxyrack.net
#smartproxy: proxy-geo-target-area = gate
proxy-geo-target-area = premium.residential
proxy-session-duration = 1
proxy-username = ishogbon
proxy-password = bc0151-0a8b75-3d55b3-329f8f-a69473
proxy-port = 10000
#smartproxy: proxy-sticky-template = user-<user>-country-<geo_target>-sessionduration-<ss_duration>-session-<ss_string>:<pass>@<geo_target_area>.smartproxy.com:<port>
#smartproxy: proxy-random-template = user-<user>:<pass>@gate.smartproxy.com:10000
proxy-sticky-template = <user>-<geo_target>-session-<ss_string>:<pass>@<geo_target_area>.proxyrack.net:<port>
proxy-random-template = <user>:<pass>@premium.residential.proxyrack.net:9000

[IDENTITY]
# the following variable dictates on what base to fetch identity, the accepted values are 'scr'(screen resolution),
# 'device_type', 'proxy_geo'(careful here), 'id'(be careful with this one - very careful). If using screen-resolution,
# no need to set value
fetch-by = scr
fetch-by-value =