[OPTIONS]
nordvpn-ovpn-files-path = /path/to/nordvpn-ovpn-files
ipvanish-ovpn-files-path = /path/to/ipvanish-ovpn-files
screen-width = 1366
screen-height = 768
up-taskbar-height = 5
debug = True
containerized = False

[WAIT_CONDITIONS]
implicitly-wait-time = 15

[EXECUTABLES]
chrome-binary-location = /executables/browsers/chrome
chrome-webdriver-location = /executables/drivers/chrome
chrome-extensions-location = /executables/extensions/chrome
firefox-binary-location = /executables/browsers/chrome
firefox-webdriver-location = /executables/drivers/geckodriver

[BOT]
bot-id = 1376-0
max-alive-time = 120
min-alive-time = 100
run-infinitely = True
engage-reader = True
# Don't touch mouse-use-probability unless you know what it does
mouse-use-probability = 0.62

[BROWSER]
chrome-data-dir =
maximum-window-probability = 0.92
# Useful for MacOS, Sets the Browser Window to Fullscreen
fullscreen-probability = 0.6

[OVPN]
max-connect-retries = 1
max-wait-time = 7

[SCROLL]
px-value = 250

[SITE]
proxy-whitelisted-domains = whouseem.com,dudialgator.com,bedrapiona.com,fleraprt.com
proxy-blacklisted-domains = googleapis,chrome,google,gstatic,gvt1,finnsec.us,googlesyndication,
proxy-blacklisted-extensions = .html,.js,.css,.jpg,.jpeg,.png,.gif,.svg,.woff,.woff2,.ttf,.ico,.webm,.ogg,.wav,.mp3,.mp4
proxy-whitelisted-mimes = */*,text/html
allow-url-through-proxy-if-matches-browser-active-url = True

[PROXY]
use-proxy = True

[IDENTITY]
# the following variable dictates on what base to fetch identity, the accepted values are 'scr'(screen resolution),
# 'device_type', 'proxy_geo'(careful here), 'id'(be careful with this one - very careful). If using screen-resolution,
# no need to set value
fetch-by = scr
fetch-by-value =

[IDENTITY_ENDPOINTS]
base-host = 

[DEBUGGING]
print-network = True