apiVersion: apps/v1
kind: Deployment
metadata:
  name: webbot
  namespace: bots
  labels:
    app: webbot
    type: ishbot
spec:
  template:
    metadata:
      name: webbot-pod
      labels:
        app: webbot
        type: ishbot
    spec:
      containers:
        - name: webbot
          image: us-east4-docker.pkg.dev/centering-rider-426308-i2/ish-bot/ish_bot:5c5a903e25c7bea3ff91b42460fca85e11ba1110
          envFrom:
            - secretRef:
                name: ish-bot-proxy-auths
          ports:
            - containerPort: 5900
              name: vnc
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
          - name: storage
            mountPath: /ebs
          - name: config-volume
            mountPath: /app/configs
            subPath: configs.ini

      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: ish-bot-ebs-pvc
      - name: config-volume
        configMap:
          name: ish-bot-config

  replicas: 1
  selector:
    matchLabels:
      type: ishbot
