
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ish-bot-ebs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ish-bot-ebs-sc
  resources:
    requests:
      storage: 100Gi