name: Build and Push to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCR_SERVICE_ACCOUNT_CREDENTIALS }}'
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker to use Google Cloud
        run: gcloud auth configure-docker 

      - name: Build and tag the Docker image
        run: |
          docker build -t ish-bot/${{ secrets.GCP_PROJECT_ID }}/ish_bot:${{ github.sha }} .

      - name: Push the Docker image
        run: |
          docker push ish-bot/${{ secrets.GCP_PROJECT_ID }}/ish_bot:${{ github.sha }}

